services:
  server:
    build:
      context: ../../../
      dockerfile: ./build/package/Dockerfile
    volumes:
      - ../../../cmd/web:/web
    environment:
      - LISTEN_PORT=9865
      - MYSQL_DSN=${IDN_REMOTE_SCHEDULER_MYSQL_DSN}
      - CLIENT_USERNAME=${IDN_REMOTE_SCHEDULER_CLIENT_USERNAME}
      - CLIENT_PASSWORD=${IDN_REMOTE_SCHEDULER_CLIENT_PASSWORD}
      - DEFAULT_NUMBERS=${IDN_REMOTE_SCHEDULER_DEFAULT_NUMBERS}
      - WA_PUBLISHER_API_BASE_URL=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_API_BASE_URL}
      - WA_PUBLISHER_API_KEY=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_API_KEY}
      - WA_PUBLISHER_API_SECRET=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_API_SECRET}
    ports:
      - "9865:9865"