services:
  server-scheduler:
    build:
      context: ../../../
      dockerfile: ./build/package/Dockerfile
    volumes:
      - ../../../cmd/web:/web
    environment:
      - LISTEN_PORT=9865
      - MYSQL_DSN=${IDN_REMOTE_SCHEDULER_MYSQL_DSN}
      - DASHBOARD_CLIENT_USERNAME=${IDN_REMOTE_SCHEDULER_CLIENT_USERNAME}
      - DASHBOARD_CLIENT_PASSWORD=${IDN_REMOTE_SCHEDULER_CLIENT_PASSWORD}
      - WA_DEFAULT_NUMBERS=${IDN_REMOTE_SCHEDULER_DEFAULT_NUMBERS}
      - WA_PUBLISHER_API_BASE_URL=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_API_BASE_URL}
      - WA_PUBLISHER_USERNAME=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_USERNAME}
      - WA_PUBLISHER_PASSWORD=${IDN_REMOTE_SCHEDULER_WA_PUBLISHER_PASSWORD}
    ports:
      - "9865:9865"